apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec: 
      containers:
      - name: nginx-container
        image: nginx:1.27.0       
        ports:
        - containerPort: 80
